export const PATH = {
  HOME: "/",
  ABOUT: "/about",
  AUTH: "/auth",
  LOGIN: "/auth/login",
  SIGN_UP: "/auth/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  CART: "/cart",
  TEST: "/test",
  PRODUCTS: "/products",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile/me",
  VIEWED_PRODUCTS: "profile/viewed-products",
  CHANGE_PASSWORD: "/profile/change-password",
  FAVORITE: "/profile/favorites",
  ORDER: "profile/order",
  CHECKOUT: "/checkout",
  OTHER: "/other",
  CONTACT: "/contact",
};

export const PAGE_TITLE = {
  HOME: "pageTitle.home",
  ABOUT: "pageTitle.about",
  SIGN_UP: "pageTitle.signUp",
  LOGIN: "pageTitle.signIn",
  TEST: "pageTitle.test",
  PRODUCT: "pageTitle.product",
  CART: "pageTitle.cart",
  OTHER: "pageTitle.other",
  CONTACT: "pageTitle.contact",
  CHECKOUT: "pageTitle.checkout",
};
